[package]
name = "cce_cik_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4"
serde_json = "^1"
tantivy = "0.17.0"